

theme: "hugo-PaperMod"
baseURL: http://hugzsoubrier.com
languageCode: en-us
title: Home
menu:
  main:
    - name: About
      url: /about/
    - name: C.V.
      url: /vitae/
    - name: Publications
      url: /publications/
    - name: Portofolio
      url: /portfolio/

boolean: false
params:
 defaultTheme: light 
 disableThemeToggle: true
 socialIcons:
     - name: email
       url: soubrierhugo@gmail.com
     - name: twitter
       url: "https://twitter.com/soubrier_hugo"
     - name: github
       url: "https://github.com/hugzsoubrier"

 profileMode:
        enabled: true
        title: "Hugo Soubrier, MSc"
        subtitle: "🦟Infectious diseases | 🌴Nature | 🗺Geography | 📖Reading"
        imageUrl: "img/volcano.PNG"
        imageWidth: 120
        imageHeight: 120
        buttons:
              - name: CV
                url: /vitae/
              - name: Portfolio
                url: /portfolio/

assets:
  favicon: favicons/apple-touch-icon.png

markup:
  goldmark:
    renderer:
      unsafe: true