---
title: "Hello !"
output: html_document
---
<html>  
<link rel="stylesheet" href="../static/css/custom.css" />
</html>

<p class="intro">Welcome to my academic website! I use it as a platform to keep track of my projects, my programming notes, my research publications as well as my readings.</p>

My name is **Hugo Soubrier** and I am from the South-East of France.  

I am interested in many things related to Nature and Biology, but it is to Infectious diseases and Epidemiology that I decided to devote my studies. 

Driven by the desire to do <strong>Field Epidemiology of Infectious diseases</strong> especially in the context of Emergencies and Response to Outbreaks. Always thriving for travels and new challenges I want to use <strong>data analytics tools</strong> to support, improve and facilitate the workflow of epidemiology on the field.

I am curious and interested in many aspects of Infectious diseases,  and I have been trying to accumulate knowledge and competence in various domains, as I truly believe that a good and complete epidemiologist needs skills spanning a wide range of domain. 

<details class="item-1">
    <summary>Microbiology and Virology</summary>
    <p>The teaching in immunology, virology and bacteriology during my BSc in Microbiology at Imperial College London, and then my MSc in Control of Infectious Diseases at the London School of Tropical Medicine (LSHTM), has given me a critical eye on the biology, ecology spread and control of infectious agents.</p>
  </details>
  
<details class="item-2">
    <summary>Epidemiology</summary>
    <p>My epidemiology competence stem from my MSc Control of Infectious Diseases at the LSHTM. It is my main subject of interest, and from the basics of epidemiology I have deepened my knowledge to Spatial Epidemiology and Epidemiology of Infectious Diseases, also Field Epidemiology and its various applications to Emergency context and Outbreaks.</p>
    
<p>The different Advanced statistics course I followed at the LSHTM have equipped me with solid theoretical foundations for my epidemiological analysis.</p>
</details>
  
  <details class="item-3">
    <summary>General Data Science</summary>
    <p>I started learning data science with self-taught resources but since then I have applied several of my skills to my university projects and recent work at Bernhard Nocht Institute of Tropical Medicine (BNITM). I am mainly focused on R and its environment (Rmarkdown, Rshiny …), but I also know SQL, Markdown, HTML and CSS. I love to learn and discover new skills and tools, as an example, I have learned how to code the current website to help me with organize my projects and store my programming notes.</p>

<p>My data science skills were reinforced on the theoretical side by strong Advanced Statistics course that I followed during my MSc at the LSHTM.</p>

  </details>
  
  <details class ="item-4">
    <summary>Spatial Data Science</summary>
    <p>Spatial data science has a very special importance for me. I love maps and geography, and therefore at LSHTM I decided to study Spatial Epidemiology. Since then, I have never stopped to practice this skill and tried to apply it to most of my projects. I am fond of map making, and other data visualization in spatial context. From my master project until my most recent publication, I am always using maps as my primary point to understand a situation or context.</p>

<p>I am comfortable with ArcGIS, QGIS, GeoDa, SatScan, but it’s mainly on R that I have conducted most of my spatial analysis. I know how to make maps as well as interactive maps from R environment and embed them in various support such as markdown reports or Shiny dashboards.</p>

<p>I also have extensive knowledge of remote-sensing data which were my primary data source for my Master project. I have used R to download, handled and analyzed data provided by Sentinel-2 and Landsat-8 satellites. Processing GeoTiff files into Temperature, Rainfall, Landcover and NDVI datasets. I have also learned to performed geographical calculation, and extract raster values for given sampled points.</p>
  </details>
  
  <details class ="item-5">
    <summary>Diagnostics</summary>
    <p>It’s my belief that any strong epidemiologist shall have a good understanding of the data collection workflow in order to identify pitfalls, biases and to fully grasp the extent of its datasets. On this basis, I have tried to be at the start of the data collection workflow, and now I can proudly say that I have a strong diagnostic experience.</p>

<p>Having worked 2 years at Bernhard Nocht Institute of Tropical Medicine in the Africa Team of the Virology department, we were specialized in diagnostic of class-4 infectious agents (Ebolaviruses, Marburgviruses, Lassa virus, Yellow Fever virus, Dengue virus…). There I was trained by the European Mobile Laboratory, for handling of class-4 pathogens in BSL-3 laboratories on the field.</p> 

<p>I have solid grounds in PCR diagnostics especially qRT-PCR, as well as in serology (IFA, ELISA). Our project of capacity building of local Diagnostic laboratory in West Africa has given me opportunities to share those skills by training local teams.</p>
  </details>
  
  <details class="item-6">
    <summary>Field work</summary>
    <p>Field work was the first experience I tried to obtain as soon as my MSc was over. I am glad to say that I have now been deployed 5 times to Guinea to respond to the Ebola Virus Disease outbreak that started in February 2021. The deployments under the Global Outbreak Alert and Response Network (GOARN) of WHO, has given me strong field experience in what could be described as intense settings.</p>

<p>I have loved my work there, and our capacity building project in Conakry and in the remote forest of Guinea has been extremely valuable to me, as much on the professional side, as on the personal side. My experience of Africa was up to my expectations, and reinforced my desire to work there on the field.</p>
  </details>
  
  




