---
title: 
author: 
date: 
slug: []
categories: []
tags: []
---

<html>  
    <link rel="stylesheet" href="/css/custom_cv.css" />
</html>

<center>
<span class="title">Hugo Soubrier</span><br>
10/02/1998<br>
+ 33 622685242<br>
<a>[soubrierhugo@gmail.com](mailto:soubrierhugo@gmail.com)</a>
</center>

------

<span class="intro">I want to use data analytics tools to support, improve and facilitate the workflow of epidemiology on the field especially in the context of Emergencies and Response to Outbreaks.</span>

------

<!-- This is the Education Section -->

<div class = "grid">
  <div class="section">Education</div>
  
  <div class="item">MSc Control of Infectious Diseases</div>
  <div class="org">London School of Hygiene and Tropical Medicine</div>
  <div class="date">2019 - 2020</div>
  <div class="description">
  
Multi-disciplinary course aiming at bridging disciplines to study and control infectious diseases.\
**Merit Distinction** - GPA: 4.01/5 (80,2% Upper-First-class honours).
 
 <details>
 <summary> more details </summary> 
 
 **Term 1:** 

- *Introduction to Disease agents and their control* 
- *Extended Epidemiology*, *Basics Statistics for Public Health* 
- *Health Policy Process and Power*.

**Term 2:**

- *Designing Disease Control Programmes in Developing Countries* - group project to design
an evidence-based WASH control programme to “ Reduce incidence diarrhoea in children under
5 in Fort-Dauphin, Madagascar"

- *Statistical Methods in Epidemiology* - Data analysis: "Does experiencing stigma increase the
risk of depression among adolescents living with HIV?” - achieved 4/5

- *Spatial Epidemiology in Public Health* - Spatial data analysis: “Descriptive spatial analysis of
soil-transmitted helminth infections in Liberian schoolchildren” - achieved 5/5

- *Epidemiology and Control of Communicable Diseases* - Disease Outbreak Investigation
group project over 2.5 days. - achieved 5/5

**Term 3:**

- *Advanced Statistical Methods in Epidemiology* - data analysis of Low respiratory Tract
Infection in Uganda Birth cohort. - achieved 4/5

**Master Project**: *Spatial distribution and environmental factors associated with Anopheles mosquitoes on the Bijagós Archipelago, Guinea-Bissau* - achieved 4/5

Objectives:

- to provide clear mapping of the main mosquito species sampled on 5 islands of Bijagos Archipelago during the dry period (November/December) 2017.

- to collect, process and map remotely-sensed environmental and climatologic data of interest for the studied islands during the study period.

- to process and handle epidemiological data collected in 2017.

- to model the association between mosquito density, epidemiological and environmental variables at each sampling sites.

- All analyses, maps and data science were performed on R.

 </details>
 
 </div>
 </div>
 
<div class = "grid">
  <div class="item">BSc Microbiology</div>
  <div class="org">Imperial College London</div>
  <div class="date">2016 - 2019</div>
  <div class="description">
  
The course covered the basics of many aspects of biological sciences. Selection of options covering Bacteriology, Virology, and Immunology allowed me to transform it into a Microbiology degree.\
**Second class Honours (Upper division)** - 69%
 
 <details>
 <summary>
 more details
 </summary>
 
 **3rd Year** - overall 69%

- *Medical Microbiology* - 75%
- *Advanced Topics in Infection and Immunity* - 68%
- *Advanced Immunology* - 73%

**Final Year Project**: *Investigation of the role of the mucosal antimicrobial response in mosquito infection with malaria parasites*. Carried out under Dr. Dina Vlachou supervision at the Vector ImmunoGenomics & Infection Laboratory (VIGILAB) at Imperial College London. achieved 63%

- dsRNA synthesis for targeted gene silencing
- handling and breeding of *Anopheles gambiae* mosquitoes
- Micro-Injection of dsRNA into living mosquitoes
- Mosquito dissection, midguts staining and observations under fluorescent microscope
- Statistical analysis, and graph generation using Prism and R 

Assessment based on designing Poster for presentation of research, Research Report ( 6,000
words) and Research Viva (15 min).


**2nd Year** - overall 69%

- *Applied molecular Biology with Bioinformatics* - 67%
- *Genetics with Statistics* - 70%
- *Virology* - 75%
- *Bacterial Physiology* - 60%
- *Immunology* - 75%

**Tutored Dissertation**: consisting of a fully referenced literature review on the topic of *Zebrafish’s gut microbiota, an emerging and advantageous model in studying gut-brain axis?* - Achieved 76%

Horizons co-curricula optional module on *History of Revolutions*.

**1st Year** 

- Biochemistry and Microbiology - 67%
- Organisms Biology - 75%
- Cell Biology and Genetics - 69%
- Evolution and Ecology - 62%

 </details>
 
 </div>
 </div>

<div class = "grid">
  <div class="item">French Baccalaureat - International option</div>
  <div class="org">Lycée International de Valbonne</div>
  <div class="date">2013-2016</div>
  <div class="description">
  
French Scientific Baccalaureat with International Options (OIB)\
**High Honours** - 17,40/20
 </div>
 </div>
 
 <hr>
 
 
<!-- This is the Experience Section -->

<div class = "grid">
  <div class="section">Experience</div>
  
  <div class="item">Research Assistant</div>
  <div class="org">Africa Team, Bernhard Nocht Institute of Tropical Medicine</div>
  <div class="date">May. 2021 - ongoing</div>
  <div class="description">
  
 Research Assistant position within the Africa Team. My role was to support the capacity building and research activities going on in Guinea. I also created a R dahsboard and SQL process to visualise / analyse the activities of laboratories. The dashboard also included analysis to follow activities per pathogen for future outbreak response. 
 
 <details>
 
 <summary> more details</summary>
 
 Involved in 5 deployment under GOARN/ WHO to support **diagnostic capacity building for EBOV outbreak response in Guinea**. 
 
The project partnered with the *Laboratoire des Fièvre Hémmoragiques Virales de Guinée (LFHVG)*, the reference laboratory based in Conakry, the  *Laboratoire des Fièvre Hémmoragiques Virales de Gueckedou (LFHV-GKD)* and the *Hopital Régional de N'Zérékoré* in the Forest regions of guinea. 
 
The main aim was to train local staff, re-organise & re-structure the laboratories as well as deliver consumables and equipment, with the objective of strengthening the diagnostic activities of Guinea regarding hemorrhagic fevers viruses: EBOV, MARV, LASV, DENV, YFV, CCHFV ...

I also conducted some scientific research on surveillance of several pathogens in forest guinea using serology. The work is still ongoing with a publication in scope. 

I was involved in the following tasks:
 
- Theoretical and practical training of local staff on diagnostics (sample reception, manipulation & inactivation, RNA extraction, Master Mix preparation and qRT-PCR runs on RotorGenes, Analysis of runs and data entry). Enhanced training on Bio-safety and manipulation under the Glovebox. 
 
- Creation of a full database system for the storage, samples, results and equipment management of the laboratories. The new databases were created according to local staff needs, and was made compatible with a later process of epidemiological/data analysis. Training of the local staff on Excel handling, and data entry. 

- Creation of a complete Dashboard on R shiny to allow visualisation / analysis of all the Laboratory activities. As well as "per pathogen" analysis for future outbreak response. 

- Support various logistic activities related to the project: Shipments, consumables ordering, storage organisation... 

- Writing and Management of several pacckages of documentation to organise the workflow of the laboratory. These included Standard Operating Procedures (SOP), Short Working Instructions (SWI), logs and forms. All writtent both in French and English for local staff. 

- Multiple Theoretical training to local staff on: Basics of Epidemiology, Diagnostic laboratory workflow, biosafety, serology, Virology of viruses of forest Guinea, Databases. 

- Multiple Infrastructure and Construction work to improve the workflow and safety in the laboratories. Construction of a one-way system to limit contamination and increase safety at the reception/ inactivation steps. 

- Multiple Electrical work to cope with electrical instability and decrease the laboratories dependence on public electricity. Work on generators and whole-laboratory electrical plans.

- General work regarding Public relationship in Africa
 
 </details>
 
 </div>
 </div>
 
<div class = "grid">
 <div class="item">Research assistant</div>
 <div class="org">LAROCS project/ BNITM</div>
 <div class="date">Nov. 2020 - May. 2021</div>
 <div class="description">
  
Research assistant on Lassa fever immunology in humans and rodents for the LAROCS project supervised by Dr. Elisabeth Fichet-Calvet.

<details>
<summary> more details </summary>

- Main project was investigating various human samples for IgG and IgM antibodies to assess the potential for urine and saliva fluids in ELISA testing as correlates to classical blood samples.

- Work in CL-2 lab, with handling and inactivation of potentially infectious humans samples under the Bio Safety Cabinet using protective equipment.

- Designed and conduct ELISA test for IgG and IgM on +1,300 samples from Guinea and Sierra Leone.

- Additional ELISA test also performed on animals samples such as whole blood rodents and ovins sera, in order to investigate the agreement between ELISA testing and gold-standard IFA for animal serology.

- Viral RNA extraction, preparation of MasterMix and q-Reverse-Transcriptase PCR for Lassa Virus detection.

- Performed descriptive statistical analysis and mapping of study area for publications


The work resulted in a first author publication in *Viruses*: **Detection of Lassa virus-reactive IgG antibodies in wild rodents: validation of a capture enzyme-linked immunological assay**

 </details>
 
 </div>
 </div>
 
<div class = "grid">
 <div class="item">UROP internship</div>
 <div class="org">Department of Infectious Disease Epidemiology, Imperial College London</div>
 <div class="date">Aug. - Sept. 2018</div>
 <div class="description">
8 weeks UROP internship in Dr Nick Croucher’s Bacteriology group at St Mary’s Hospital campus of Imperial College London, Departement of Infectious Disease Epidemiology.

 <details>
 <summary> more details</summary>

- Research project focused on the S. pneumoniae competence system.

- Worked with potentially pathogenic samples in a CL-2 lab

- Designed and conducted experiments on *S. pneumoniae*.

- Site-directed mutagenesis, gene cloning, PCR, preparation and plating of bacteria, colonies counting, handling of protoplasts

- Produced a detail protocol for the generation of *S. pneumoniae* protoplasts, and generation of mutated endA gene, for study of competence asymmetry.

 </details>
 
 </div>
 </div>
 
<div class = "grid">
 <div class="item">Tutoring sessions for Science</div>
 <div class="org">All levels - Preparation International Baccalaureate</div>
 <div class="date">2016 - 2020</div>
 <div class="description">
  
Sharing Knowledge and preparation for the final year exams of French and English: Baccalauréat, A-levels and IB, in Physics-Chemistry, Biology, Geology, and History.
 
 </div>
 </div>
 
<div class = "grid">
 <div class="item">Summer volunteering</div>
 <div class="org">South African Game reserve</div>
 <div class="date">2014 & 2015</div>
 <div class="description">
  
 2 x 3 months Summer volunteering to help with animal monitoring and conservation in South African game reserves.
 
 <details>
 <summary> more details</summary>
- Balule reserve, Kruger National Park and Zululand

- Help with the conservation of endangered species.

- Daily tracking, monitoring and identification of the main endangered species in the reserves

- Handling of animals, and carcasses for hygiene purposes - prevention disease outbreak
 </details>
 
 </div>
 </div>
 
 <hr>
 
<!-- This is the Publications Section -->

<div class = "grid">
 <div class="section">Publications</div>
 <div class="item">
 
 - First publication
 - Second Publications
 
 </div>
 </div>

<hr>

<!-- This is the Skills Section -->

<div class = "grid">
 <div class="section">Specific Skills</div>
 <div class="item"> Languages </div>
 <div class ="description"> 
 
- French : native speaker 
- English : fluent
- Spanish : very good comprehension and good speaking ability
 
 </div>
 
 </div>

<div class = "grid">
 <div class="item"> Data science </div>
 <div class ="description"> 
 
 <details>
 <summary> details of skills & softwares</summary>
<h5>R</h5> 
Strong R skills for data sciences especially using Pipes and the Tidyverse. Experience of R markdown, R shiny, R Blogdown. 

Strong R skills for Epidemiology analysis using resources from R4Epi, RECON and Epidemiologist R Handbook packages. I have used R to generate analysis report, graph-making and dashboards for data analysis

<h5>SQL</h5>
Experience of SQL querying especially with postgres SQL. I have used it to as a way of centralising data, and connected my databases to a R shiny dashboard. 

<h5>HTML/CSS</h5>
Experience of HTML to modify a markdown file, and create websites using R. CSS stylesheet created to customise the Markdown documents, shiny App and website.
 </details>
 </div>
 </div>
 
 <div class = "grid">
 <div class="item"> Spatial Data science </div>
 <div class ="description"> 
 
 <details>
 <summary>details of skills & softwares</summary>
<h5>R</h5> 
Strong R skills for spatial displaying, and analysis, including use and analysis of
remote-sensing data. 

<h5>Other Softwares </h5> 

Very Good understanding of ArcGIS, QGIS, GeoDa and
SatScan used in severl projects.

<h5>Illustrator</h5>
Used for final map-making refinements. 
</details>
 </div>
 </div>
 
 <div class = "grid">
 <div class="item"> Other Softwares of Interests</div>
 <div class ="description"> 
 
- ODK/Enketo for questionnaire designing
- Basics phylogenetics analysis using BEAST and associated softwares (Beauti, Tracer, FigTree…)
- Sequence visualiser softwares: ARTEMIS / Snap Gene
 
 </div>
 </div>
 
 
 <div class = "grid">
 <div class="item"> Laboratory work</div>
 <div class ="description"> 
 
- Manipulation of pathogenic samples - BSC-L2 / BSC-L3.
- Work under the glovebox for manipulation of Class-4 pathogens
- diagnostics workflow: Sample reception/inactivation, RNA extraction, MM preparation, q-RT-PCR, result interpretation
- serology workflow: ELISA and IFA testing. 
 
 </div>
 </div>
 
<div class = "grid">
<div class="item"> Field Work & Deployments</div>
<div class ="description"> 
 
- item 1

- item 2
 
 </div>
 </div>
 
<div class = "grid">
<div class="item"> Diplomas & Trainings</div>
<div class ="description"> 
 
Mandatory Online Certificates for **deployment under WHO/GOARN**:

- BSAFE
- GO certificate for Ebola response
- Serve with Pride
- Prevention of Harassment and Abuse by UN personnel - Working harmoniously
- UN Human Right Responsibilities
- GOARN tier 1 course

**Online training for Ethic Research- LSHTM** 

Short online course, with online examination about the Ethics in Science, with a emphasis on Epidemiological research. Resulted in a Certificate of Ethics Research.
 
 
**GIS course at LSHTM**

participated in short-course on the introduction to GIS and Spatial Analysis, using ARC-GIS.

**LonWHO 2019** 

3 days WHO simulation conference. Themed on “Conflict and Health”. Represented the pharmaceutical company PFIZER, which approval was required for countries resolution. Lobby work to ensure the company interest are reflected in resolutions tackling health aspects in conflict zone. The conference gave a great understanding of diplomacy, and global health governance.

 </div>
 </div>
 
<hr>

<!-- This is the Interests Section -->

<div class = "grid">
 <div class="section">Interests</div>
 <div class="description">
 
**Leadership**: Captain of IC Fencing Men’s second Team.

- 16 years of Fencing, participated in National and International competitions (France).
 
- Member of IC Fencing team 3 years in a row, winners of 2018 South-Eastern Conference Cup
and South-Eastern 2A league, got promoted to South-Eastern 1A league.

- Organisation of Trainings and Travels.
 
International PADI license. Level 1, 25+ scuba diving and nocturnal divings. Amateur of sailing, freediving
and spearfishing.

Historical, Geographic, Philosophical and Scientific readings.

 </div>
 </div>








