---
title: "List of books"
author: 
date: "4/11/2022"
output: html_document
---

<html>  
<link rel="stylesheet" href="/css/custom_books.css" />
</html> 

<br>

I keep this list of books that I have read for my own references. 

<div class="grid">
<div class="reference"> 
<span class = "title">Peste et Choléra</span> - <span class = "author">Patrick Deville </span>, <span class = "edition">Gallimard, </span><span class = "date"> 2019 </span> </div>
<div class="description">description</div>
</div>

<div class="grid">
<div class="reference"> 
<span class="title">Tristes Tropiques</span> - <span class="author">C. Lévis Strauss, </span><span class = "edition">Terre Humaines Poches, </span><span class = "date"> XX </span></div>
<div class="description">description</div>
</div>

<div class="grid">
<div class="reference"> 
<span class="title">Brief History of Time</span> - <span class="author">Stephen Hawking, </span><span class = "edition">XXX, </span><span class = "date"> XX </span></div>
<div class="description">description</div>
</div>

<div class="grid">
<div class="reference"> 
<span class="title">Prisoners of Geography</span> - <span class="author">T. Marshall, </span><span class = "edition">XXX, </span><span class = "date"> XX </span></div>
<div class="description">description</div>
</div>

<div class="grid">
<div class="reference"> 
<span class="title">The rules of Contagions</span> - <span class="author">A. Kucharski, </span><span class = "edition">XXX, </span><span class = "date"> XX </span></div>
<div class="description">description</div>
</div>

<div class="grid">
<div class="reference"> 
<span class="title">Les derniers rois de Thulés</span> - <span class="author">J. Malaurie, </span><span class = "edition">XXX, </span><span class = "date"> XX </span></div>
<div class="description">description</div>
</div>

<div class="grid">
<div class="reference"> 
<span class="title">Les derniers rois de Thulés</span> - <span class="author">J. Malaurie, </span><span class = "edition">XXX, </span><span class = "date"> XX </span></div>
<div class="description">description</div>
</div>



- Other Minds- Peter Godfrey smith

- No Time to lose- Peter Piot

- Why we sleep- Matthew Walker

- Digital Minimalism- Cal Newport 

- L’Erebus - Michael Palin 

- Le désert des Déserts- W. Thesiger

- Magellan - Stefan Zweig

- Expert - Roger Kneebone 

- Wayfinding - Michael Bond

- Introduction au Pensées de Marc-Auréle- P. Hadot

- The Life and Death of Ancient Cities- Greg Woolf

- Kindred, Neanderthal Life, Love, Death and Art - R. Wragg Sykes 

- Fièvre de Lassa- Dr. Saltzmann

- Kampuchéa - Patrick Deville 

- Un été avec Homère - Sylvain Tesson

- Equatoria - Patrick Deville 

- Race et Histoire - Claude Levi-Strauss 

- L’insoutenable légèreté de l’être - Milan Kundera 

- Le courage de la Nuance - Jean Birnbaum

- Homo Domesticus - James Scott

- Le bateau de Palmyre - Maurice Sartre 

- Petit Éloge de l’Anarchisme - James Scott

- Fouché- Stefan Sweig




PHILOSOPHIE 

- Epicure. Lettre à Ménécée 

- Lucrèce. De la nature 

- Les pensées de marc Auréle 

- Sénèque. De la brièveté de la Vie




